plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - about.md
  - contact.md
remote_theme: deandrawhitby/documentation-theme-jekyll-next-version

